services:
  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'

  wardrobe-api-gateway:
    build:
      context: .
      dockerfile: ./apps/wardrobe-api-gateway/DockerFile
      target: development
    command:  npm run start:dev wardrobe-api-gateway
    env_file:
      - ./apps/wardrobe-api-gateway/.env
    depends_on:
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'

  wardrobe:
    build:
      context: .
      dockerfile: ./apps/wardrobe/DockerFile
      target: development
    command:  npm run start:dev wardrobe
    env_file:
      - ./apps/wardrobe/.env
    depends_on:
      - rabbitmq
      - wardrobe-api-gateway
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules