export enum ItemType {
  Hoodie = 'hoodie',
  Jacket = 'jacket',
  Coat = 'coat',
  TShirt = 't-shirt',
  Shirt = 'shirt',
  Sweater = 'sweater',
  Blazer = 'blazer',
  Pants = 'pants',
  Jeans = 'jeans',
  Shorts = 'shorts',
  Skirt = 'skirt',
  Dress = 'dress',
  Suit = 'suit',
  Vest = 'vest',
  TankTop = 'tank top',
  Cardigan = 'cardigan',
  Tracksuit = 'tracksuit',
  Overalls = 'overalls',
  Raincoat = 'raincoat',
  Windbreaker = 'windbreaker',
  Polo = 'polo',
}
