# syntax=docker/dockerfile:1
FROM node:20-alpine AS base
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .

FROM base AS development
CMD ["npm", "run", "start:dev", "ai-assistant"]

FROM base AS production
RUN npm run build ai-assistant
CMD ["node", "dist/apps/ai-assistant/main.js"]

